### PR TITLE
SNP-07/Product-pages

### PR DESCRIPTION
**Pull request by tomasdrga**
Pridal som about pages a podobne, nech mame nejaky landing page, upravene routes

### CODE REVIEW

**Comment by tomasdrga** [comment]
About page
Screenshot 2024-10-15 at 19-05-37 SeenUp

**Comment by tomasdrga** [comment]
Contact page
Screenshot 2024-10-15 at 19-05-49 SeenUp

**Comment by tomasdrga** [comment]
Privacy page

**Comment by tomasdrga** [comment]
Privacy page
Screenshot 2024-10-15 at 19-05-58 SeenUp

**Comment by matejdrienovsky** [comment]
> About page Screenshot 2024-10-15 at 19-05-37 SeenUp

@tomasdrga Pekny sme tam hehe

**Comment by matejdrienovsky** [comment]
> About page Screenshot 2024-10-15 at 19-05-37 SeenUp

@tomasdrga Pekni sme tam hehe

**Comment by matejdrienovsky** [comment]
> Contact page Screenshot 2024-10-15 at 19-05-49 SeenUp

@tomasdrga Pobavil som sa

**Review by matejdrienovsky — APPROVED** [review]

**Comment by matejdrienovsky** [comment]
@tomasdrga mozes mergovat

**Pull request merged**
